### ISSUE TITLE
Adding DENSITY type sparklines to Fx:  gt_plt_summary(DF) 

### ISSUE THREAD

**Issue by sfd99** [jthomasmock/gtExtras#105]
**_Hi Tom,_**

Thanks for the wonderful, 
super-useful **gtExtras** PKG!.

**quick Q:**
Any chance to allow
the function:
    gt_plt_summary(DF)
to display:
   Density plot sparklines
(instead of only the current default bars sparklines ).

Maybe w/ an optional arg:  
    "density" (default)
      -or- 
    "bars" ?.

EX:
gt_plt_summary(DF,  type = "density")   # or type = "bars"

_Thanks, Tom!!_
**sfd99
San Francisco
Latest R / Rstudio
Ubuntu LINUX 20.04
gtExtras PKG v: 0.5.0**

**Comment by jthomasmock** [comment]
Thanks for the request! `gt_plt_summary()` is focused on histograms. I'll close this for now but see if there's additional interest.
