### ISSUE TITLE
Fix for issue #104 (gt_plt_summary(): can fail to plot overview for numeric data due to binwidth computation failure) creates unwanted histograms

### ISSUE THREAD

**Issue by tjkelman** [jthomasmock/gtExtras#111]
in gt_plt_summary():  The solution to issue #104, which uses `hist() `to compute the breaks when bw is zero, works great but generates separate histogram plots for all variables in which this condition is true (due to `hist` generating histogram plots unless you tell it not to).  I *think* the fix is just adding plot=FALSE in the call to `hist()`...?

**Comment by jthomasmock** [comment]
Thanks!

**Comment by laresbernardo** [comment]
+1 thanks
