### ISSUE TITLE
Manually omitting columns from output of gt_plt_summary()?

### ISSUE THREAD

**Issue by emilyrosenthal** [jthomasmock/gtExtras#112]
## Question
Is it possible to omit column(s) from the final gt_plt_summary() object (e.g., to omit the 'value' or 'missing' columns)? If so, how would one do so? Thank you!

**Comment by jthomasmock** [comment]
Howdy @emilyrosenthal - not at this time. It's kind of an "all or nothing" approach for summary statistics.

However, you can do this manually with `gt::cols_hide()`:

```r
# example reprex
library(gtExtras)

# hide the value column
> mtcars |> gt_plt_summary() |> gt::cols_hide(value)

# hide missing column
> mtcars |> gt_plt_summary() |> gt::cols_hide(n_missing)
```
