### ISSUE TITLE
gt_plt_bar_stack font

### ISSUE THREAD

**Issue by ScaonE** [jthomasmock/gtExtras#119]
Dear all,

Is there a way to change the font for numbers within the stacked barplot? (I wish to use Nunito to have the same font everywhere in my doc).

(asking because I cannot control it via : opt_table_font(font = google_font(name = "Nunito Sans")))

**Comment by jthomasmock** [comment]
Howdy @ScaonE -- the numbers are hardcoded as `family='mono'` as seen in:

https://github.com/jthomasmock/gtExtras/blob/e810e592571571fde2745194f007574d8c51bfdc/R/gt_pct_bar.R#L120-L124

I'm adding a new `font` argument, and here's it with `Nunito`

![image](https://github.com/jthomasmock/gtExtras/assets/29187501/4eb5293f-6c8c-4ebe-b85c-c4491384f420)

vs the default `mono`:

![image](https://github.com/jthomasmock/gtExtras/assets/29187501/55edec8a-66ca-4466-8388-776bcfa2ffdb)
