### ISSUE TITLE
Feature Request: Allow for missing row in `gt_sparkline()`

### ISSUE THREAD

**Issue by ddsjoberg** [jthomasmock/gtExtras#13]
Hello! gtExtras is so cool and cute! 

How do you feel about allowing a missing row in `gt_sparline()`? For example, in the example below, the second row is all missing, and I would like to see the image in the first and third rows and a blank second row. (I get an error if `list(NA)` is replaced with `NULL`.)

What do you think? 

``` r
library(gt)

mtcars %>%
  dplyr::group_by(cyl) %>%
  # must end up with list of data for each row in the input dataframe
  dplyr::summarize(mpg_data = list(mpg), .groups = "drop") %>%
  dplyr::mutate(
    mpg_data = list(mpg_data[[1]], list(NA), mpg_data[[3]])
  ) %>%
  gt::gt() %>%
  gtExtras::gt_sparkline(mpg_data)
#> Warning in strsplit(x, split = ", ") %>% unlist() %>% as.double(): NAs
#> introduced by coercion
#> Warning in max(vals, na.rm = TRUE): no non-missing arguments to max; returning
#> -Inf
#> Warning in min(vals, na.rm = TRUE): no non-missing arguments to min; returning
#> Inf
#> Error in if (med_y_rnd > 0) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2021-10-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jthomasmock** [comment]
Wow, thanks for asking about this!

I've added a lightweight "blank return" if a NA or NULL is for that row.

Using `gtExtras` v 0.2.17, with your example (slightly modified to include a `NA` _and_ a `NULL`).

It now returns the below without a warning/error:

``` r
library(tidyverse)
library(gt)
library(gtExtras)

input_data <- mtcars %>%
  dplyr::group_by(cyl) %>%
  # must end up with list of data for each row in the input dataframe
  dplyr::summarize(mpg_data = list(mpg), .groups = "drop") %>%
  dplyr::mutate(
    mpg_data = list(mpg_data[[1]], list(NA), list(NULL))
  )

input_data %>% 
  gt() %>% 
  gt_sparkline(mpg_data) %>% 
  gtsave("ex.png")
```

![](https://i.imgur.com/m3RFUUN.png)

<sup>Created on 2021-10-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
Hello Again @jthomasmock !

Thank you for this update! It's been great! I noticed that this code works flawlessly for sparkline and histogram, but errors with `type = "density"`

``` r
library(tidyverse)
library(gt)
library(gtExtras)

input_data <- mtcars %>%
  dplyr::group_by(cyl) %>%
  # must end up with list of data for each row in the input dataframe
  dplyr::summarize(mpg_data = list(mpg), .groups = "drop") %>%
  dplyr::mutate(
    mpg_data = list(mpg_data[[1]], list(NA), list(NULL))
  )

input_data %>% 
  gt::gt() %>% 
  gtExtras::gt_sparkline(mpg_data, type = "density")
#> Error in quantile.default(as.numeric(x), c(0.25, 0.75), na.rm = na.rm, : missing values and NaN's not allowed if 'na.rm' is FALSE
```

<sup>Created on 2021-10-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jthomasmock** [comment]
Thanks for heads up! I've added another internal early `return()` and added this to tests. Working as seen below in latest package version.

``` r
library(gt)
library(gtExtras)

input_data <- mtcars %>%
  dplyr::group_by(cyl) %>%
  # must end up with list of data for each row in the input dataframe
  dplyr::summarize(mpg_data = list(mpg), .groups = "drop") %>%
  dplyr::mutate(
    mpg_data = list(mpg_data[[1]], list(NA), list(NULL))
  )


# Spark -------------------------------------------------------------------

input_data %>%
  gt::gt() %>%
  gt_sparkline(.data$mpg_data, type = "sparkline") %>%
  gt::gtsave("temp-spark.png")
```

![](https://i.imgur.com/d5Z1ubt.png)

``` r
# Histogram ---------------------------------------------------------------

input_data %>%
  gt::gt() %>%
  gt_sparkline(.data$mpg_data, type = "histogram") %>%
  gt::gtsave("temp-hist.png")
```

![](https://i.imgur.com/TABf1Fj.png)

``` r
# Density -----------------------------------------------------------------

input_data %>%
  gt::gt() %>%
  gt_sparkline(.data$mpg_data, type = "density") %>%
  gt::gtsave("temp-dens.png")
```

![](https://i.imgur.com/RcwLYwo.png)

<sup>Created on 2021-10-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
you are amazingly quick! thank you! looks great!

**Comment by ddsjoberg** [comment]
The gtsummary + gtExtras + sparkline table looks super cute 😍 

```r
trial %>%
  select(age, marker) %>%
  tbl_summary(missing = "no") %>%
  add_sparkline()
```
![image](https://user-images.githubusercontent.com/26774684/137823170-2216c9af-3594-4069-a11f-a523bdcf7487.png)
http://www.danieldsjoberg.com/bstfun/reference/add_sparkline.html

**Comment by jthomasmock** [comment]
Glad it's working in `gtsummary` now!
