### ISSUE TITLE
Put some numbers in gt_sparkline

### ISSUE THREAD

**Issue by IvoVillanueva** [jthomasmock/gtExtras#15]
Hello
I would like to put in the points the numbers to which it refers, as Max and Min for exemple,. I'm doing
 this table but i think the sparkline doesn't explain much without the numbers in the points blue and reds
thank you

![final_df](https://user-images.githubusercontent.com/56939175/137151676-faa96902-70ca-4444-8625-b72a1648f973.png)

**Comment by jthomasmock** [comment]
Hi @IvoVillanueva in the latest version of `gtExtras`, there is a number attached to the end of the `sparkline` to indicate the last value. 

``` r
library(gt)
library(gtExtras)
packageVersion("gtExtras")
#> [1] '0.2.18'

mtcars %>%
    dplyr::group_by(cyl) %>%
    # must end up with list of data for each row in the input dataframe
    dplyr::summarize(mpg_data = list(mpg), .groups = "drop") %>%
    gt() %>%
    gt_sparkline(mpg_data) %>% 
  gtsave("test-img.png")
```

![](https://i.imgur.com/p5p1rE3.png)

<sup>Created on 2021-10-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
