### ISSUE TITLE
Colors not applying within gt_plt_winloss()

### ISSUE THREAD

**Issue by adamkemberling** [jthomasmock/gtExtras#16]
This may be me just bumping into where active development is happening, but the colors argument for `gt_plt_winloss()` does not adjust the colors. They are hard-coded in currently here:

    input_data <- data.frame(
      x = 1:length(vals),
      xend = 1:length(vals),
      y = ifelse(vals == 0.5, 0.4, vals),
      yend = ifelse(vals == 0, 0.6, ifelse(vals > 0.5, 0.4, 0.6)),
      color = ifelse(vals == 0, "#D50A0A", ifelse(vals == 1, "#013369", "grey"))
    )

Thank you for the package!

**Comment by jthomasmock** [comment]
Thanks @adamkemberling - I've pushed an update that removes the hard-coded values 🤦  and respects the documentation of `colors= c(color1, color2, color3)`.

I've added a unit-test for color on that function to hopefully prevent future problems.
