### ISSUE TITLE
Increase column labels font size in nytimes theme

### ISSUE THREAD

**Issue by Jes-Lop** [jthomasmock/gtExtras#27]
Maybe this is not the right place to ask but, is it possible to increase the font size on the column labels? I'm trying with 
`gt_theme_nytimes(column_labels.font.size = 14)`, but it doesn't work. Any tip? Thanks!

**Comment by jthomasmock** [comment]
Hi @Jes-Lop - I'm refactoring the themes, once I release the next version you should be able to use code like the below:

```
mtcars %>% 
  head() %>% 
  gt() %>% 
  gt_theme_nytimes() %>% 
  tab_options(
    column_labels.font.size = 24
  )
```

**Comment by Jes-Lop** [comment]
Thanks @jthomasmock
