### ISSUE TITLE
Allow "colours" in gt_plt_winloss

### ISSUE THREAD

**Issue by KittJonathan** [jthomasmock/gtExtras#29]
Hi ! Would it be possible to allow for "colours" argument, as in gt_plt_winloss(colours = c()) ?

**Comment by jthomasmock** [comment]
Hi there! Going to spend some time over the break revamping and increasing consistency across the various functions - thanks for the suggestion.

**Comment by jthomasmock** [comment]
Hi @KittJonathan - can you clarify your needs here?

`gt_plt_winloss()` has a `colors` argument, which accepts the colors for the "win", "loss", "tie".

https://jthomasmock.github.io/gtExtras/reference/gt_plt_winloss.html

> colors | A character vector of length 3, specifying the colors for win, loss, tie in that exact order.

**Comment by KittJonathan** [comment]
Hi @jthomasmock, I was thinking about the "american" and "british" versions : coulors and colours
