### ISSUE TITLE
Allow `gt_sparkline` to plot multiple density curves in one plot

### ISSUE THREAD

**Issue by jorgesinval** [jthomasmock/gtExtras#30]
Is it possible to somehow plot multiple density curves in one plot using `gt_sparkline`?
Something like this:

![image](https://user-images.githubusercontent.com/8278071/145314546-bf49ab95-e99d-4b1d-8d50-ce0d66dbd158.png)

**Comment by jthomasmock** [comment]
Hi @jorgesinval - this is a cool idea! However, it's not something I'm likely to incorporate as the core functionality is one row and one graphic. You can always "escape" out to using `gt` + `gt::ggplot_image()` if you'd like to embed custom graphics or combined graphics as you're intending.

Thanks!
