### ISSUE TITLE
Option to control color of last point in `gt_sparkline()`

### ISSUE THREAD

**Issue by z3tt** [jthomasmock/gtExtras#32]
Hi Thomas, thanks for this great package! 

Related to #31 I would like to suggest an option to control the color of the non-extreme points in the `gt_sparkline()` function. Currently, there are arguments for `line_color` and `range_color` with the latter being a "vector of two valid color names or hex codes" but I couldn't find any way to control the color of the last point (and, in case #31 may be implemented in the future, also the color of the intermediate points).

**Comment by jthomasmock** [comment]
Thanks!

I'm going to consolidate the color options and palette into a single vector of colors, as opposed to many arguments. These will be then subsetted by position internally in the function.

The current plan is a vector of length 5:
- line color, final point color, low value, high value, type color

The `type_color` will be used for interquantile range area (ie tufte style 0.25/0.75 range), filled area/shaded sparklines, median/mean reference line.

Does that align with your needs/suggestions?

**Comment by jthomasmock** [comment]
See the plot options below
![points](https://user-images.githubusercontent.com/29187501/146075076-40a29ddb-eb99-4df1-9b67-8333d61b35ec.png)
![shaded](https://user-images.githubusercontent.com/29187501/146075079-5b1249b1-f7c5-4b6f-942e-d2759d8dc658.png)
![median](https://user-images.githubusercontent.com/29187501/146075082-6abecdd2-7196-4976-9d48-35133907cec4.png)
![iqr](https://user-images.githubusercontent.com/29187501/146075083-d12df1b0-85d2-41a8-9901-e916b0ad143b.png)
:

**Comment by jthomasmock** [comment]
Howdy @z3tt - note the new behavior, I have split out `gt_sparkline()` into two functions, `gt_plt_dist()` for distributions (ie boxplot, density, histogram) and `gt_plt_sparkline()` for more traditional sparklines.

For your desired behavior, option 1 with the new `pal` argument.

``` r
library(gt)
library(gtExtras)

mtcars %>%
  dplyr::group_by(cyl) %>%
  # must end up with list of data for each row in the input dataframe
  dplyr::summarize(mpg_data = list(mpg), .groups = "drop") %>%
  gt() %>%
  gt_plt_sparkline(mpg_data,
    # note the colors - grey line, blue end points with blue label
    # purple low val, green high value, and blue "type" value 
    # where type is not used in the default
    pal = c("grey", "blue", "purple", "green", "blue")) %>% 
  gtsave("test.png")
```

![](https://i.imgur.com/1jgQCyx.png)

<sup>Created on 2021-12-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
