### ISSUE TITLE
Sparkline is not sensitive to data fluctuation

### ISSUE THREAD

**Issue by ahbon123** [jthomasmock/gtExtras#34]
For the following data, we can see the data fluctuate slightly, but the plot spark is almost a straight line, is it possible to solve this issue? Sincere thanks.
```
library(dplyr)
library(gt)
library(gtExtras)

df <- structure(list(type = c("v1", "v2"), `2017-06` = c(244.955, 1.2), `2017-07` = c(250, 1.5), `2017-08` = c(252, 1.8
), `2017-09` = c(245, 0.5)), class = "data.frame", row.names = c(NA, -2L))

df %>%
  rowwise() %>%
  mutate(data = list(c_across(-type))) %>%
  select(type, data) %>%
  gt() %>%
  gt_sparkline(data)
```

![1639964605(1)](https://user-images.githubusercontent.com/15428667/146700144-c498eb97-8282-4157-9c7f-b1a643b7d08e.png)

**Comment by jthomasmock** [comment]
Howdy! Per the [`gt_sparkline` docs](https://jthomasmock.github.io/gtExtras/reference/gt_sparkline.html), you'll likely want to make use of the `same_limit` argument.

> same_limit | A logical indicating that the plots will use the same axis range (TRUE) or have individual axis ranges (FALSE).

``` r
library(dplyr)
library(gt)
library(gtExtras)

df <- structure(list(type = c("v1", "v2"), `2017-06` = c(244.955, 1.2), `2017-07` = c(250, 1.5), `2017-08` = c(252, 1.8
), `2017-09` = c(245, 0.5)), class = "data.frame", row.names = c(NA, -2L))

df %>%
  rowwise() %>%
  mutate(data = list(c_across(-type))) %>%
  select(type, data) %>%
  gt() %>%
  gt_sparkline(data, same_limit = FALSE) %>% 
  gtsave("test.png")
```

![](https://i.imgur.com/rRnmNdr.png)

<sup>Created on 2021-12-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
