### ISSUE TITLE
Function to embed ggplots in gt

### ISSUE THREAD

**Issue by lbenz730** [jthomasmock/gtExtras#35]
Hi Tom,

Thanks for all your hard work on the gtExtras package. I am wondering if it would be fairly straightforward to add a function that makes a column of user supplied charts a column in the table w/in a gt. I have done an example of this [here](https://twitter.com/recspecs730/status/1475125868171251714?s=20), by saving image files out (via `ggsave`) and then manually loading them in and using `text_transform` to create a column with the graphs as cells. 

The motivation behind such a function would be allow give a lot of flexibility to the user, and not all charts would need to be the same type, nor would the gtExtras package be responsible for the creation of the chart(s) in question. 

I am not exactly certain how this would work in your API but I imagine something like the following steps:
* Take as input a list of plot objects from the user, equal in length to the # of rows in the table/df
* saves each out locally as image file
* uses `text_transform` to create column of graphs
* deletes local images

Some challenges I would anticipate:
* getting sizing correct (perhaps a user specified `width` argument could be of use) 

I don't know what kind of effort this would require, and its definitely an enhancement request, not a bug. Thanks for all your efforts!

--Luke

**Comment by jthomasmock** [comment]
Howdy! This is already largely possible via `gt::ggplot_image()`

https://gt.rstudio.com/reference/ggplot_image.html

It uses `text_transform()` + `ggplot_image()` to embed user-defined plots.

**Comment by lbenz730** [comment]
Oh thanks for point this out. I agree the functionality requested would likely be mostly redundant
