### ISSUE TITLE
Tiny typo in the install chunk

### ISSUE THREAD

**Issue by robertwwalker** [jthomasmock/gtExtras#4]
Under installation, it reads:

```
# if needed install.packages("remotes)
remotes::install_github("jthomasmock/gtExtras")
```

The quotes need closing in the commented line for cut and paste.

```
# if needed install.packages("remotes")
remotes::install_github("jthomasmock/gtExtras")
```

**Comment by jthomasmock** [comment]
Closing this, thanks so much! I had to rebuild the readme.html for the site - so closing the issue as well.
