### ISSUE TITLE
Allow 'auto' as an option for height (or width) in `img_header`

### ISSUE THREAD

**Issue by SCasanova** [jthomasmock/gtExtras#40]
For shiny applications it would be useful to be able to set auto for either of those properties so different images fit the table header.

**Comment by jthomasmock** [comment]
Howdy @SCasanova thanks for the report! I'm not sure I'm following, is there a specific function you are referencing? Can you provide a `reprex` of the behavior?

**Comment by jthomasmock** [comment]
Howdy @SCasanova - I might be missing the issue here.

When using differently sized width/height images they are normalized to a shared height with varying widths (since the images are wider or narrower).

``` r
library(gt)

base_tab <- dplyr::tibble(
  a = 1, b = 2, c = 3
) %>% 
  gt()

test_img <-  base_tab %>%
  cols_label(
    a = gtExtras::img_header("3 brownies", "https://i.imgur.com/tI5jq2c.jpg"),
    b = gtExtras::img_header("5 waffles", "https://i.imgur.com/37w80TG.jpg"),
    c = gtExtras::img_header("1 cake bite", "https://i.imgur.com/B1MCOtx.jpg")
  ) %>%
  gtExtras::gtsave_extra("test.png", selector = "table")

magick::image_read("test.png")
```

![](https://i.imgur.com/kJgUwin.png)

``` r


tab1 <- base_tab %>%
  tab_header(title = gtExtras::img_header("3 brownies", "https://i.imgur.com/tI5jq2c.jpg")) |> 
  gtExtras::gtsave_extra("head1.png", selector = "table")

tab2 <- base_tab %>%
  tab_header(title = gtExtras::img_header("5 waffles", "https://i.imgur.com/37w80TG.jpg")) %>%
  gtExtras::gtsave_extra("head2.png", selector = "table")

img1 <- magick::image_read("head1.png")
img2 <- magick::image_read("head2.png")

magick::image_append(c(img1, img2))
```

![](https://i.imgur.com/uvMQuGN.png)

<sup>Created on 2022-05-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jthomasmock** [comment]
Closing for now as I believe it's working for different sized images.
