### ISSUE TITLE
`NA` values break `gt_plt_conf_int()`

### ISSUE THREAD

**Issue by jmbarbone** [jthomasmock/gtExtras#52]
Using the example from `?gt_plt_conf_int` with `NA` values added. 

``` r
library(gtExtras)
packageVersion("gtExtras")
#> [1] '0.4.0'

dplyr::tibble(
  mean = c(12, 10, NA), 
  ci1 = c(8, 5, NA),
  ci2 = c(16, 15, NA),
  ci_plot = c(12, 10, NA)
) %>%
  gt::gt() %>%
  gt_plt_conf_int(
    ci_plot,
    c(ci1, ci2),
    palette = c("red", "lightgrey", "black", "red")
  )
#> Error in if (zero_range(range)) zero_width else diff(range): missing value where TRUE/FALSE needed

# might need to wrap with !isFALSE
scales::zero_range(range(NA))
#> [1] NA
```

<sup>Created on 2022-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jthomasmock** [comment]
Thanks for report/reprex @jmbarbone !

I would recommend omitting NA values (ie `na.omit()`) for now but I have a fix in local dev version and am doing more testing. 

The function has a min/max call and adding `na.rm=TRUE` solves for this problem.
