### ISSUE TITLE
gt_merge_stack not working correctly

### ISSUE THREAD

**Issue by brett250000** [jthomasmock/gtExtras#55]
It appears that the gt_merge_stack function is not working correctly if you are grouping first by another field.  I was just looking at the example with NFL teams and noticed that the Ravens are not in the NFC West.
![image](https://user-images.githubusercontent.com/107630144/174087745-4b11ecd6-97ec-453d-9c67-1d2233f9efcb.png)

Worth noting that if you don't group by conference, the gt_merge_stack field displays correctly.
![image](https://user-images.githubusercontent.com/107630144/174087566-fc8cec74-2429-40aa-9a7b-cdb17034f8e2.png)

```
library(gt) 
library(gtExtras)

team_df <- readRDS(url("https://github.com/nflverse/nflfastR-data/raw/master/teams_colors_logos.rds"))

team_df %>%
  dplyr::select(team_nick, team_abbr, team_conf, team_division, team_logo_wikipedia, team_wordmark) %>%
  gt(groupname_col = "team_conf") %>%
  # gt() %>%
  gt_merge_stack(col1 = team_nick, col2 = team_division) %>%
  gt_img_rows(team_logo_wikipedia) %>%
  gt_img_rows(team_wordmark)
```

**Comment by jthomasmock** [comment]
Thanks for heads up! Please install latest dev version for fix - that function is now using `gtExtras::gt_index()` internally which is group-safe.

``` r
library(gt) 
library(gtExtras)

team_df <- readRDS(url("https://github.com/nflverse/nflfastR-data/raw/master/teams_colors_logos.rds"))

set.seed(36)
team_df %>%
  dplyr::slice_sample(n = 12) %>%
  dplyr::select(team_nick, team_abbr, team_conf, team_division, team_logo_wikipedia, team_wordmark) %>%
  gt(groupname_col = "team_conf") %>%
  gt_merge_stack(col1 = team_nick, col2 = team_division) %>%
  gt_img_rows(team_logo_wikipedia) %>%
  gt_img_rows(team_wordmark) 
```

![](https://i.imgur.com/CWDdG2e.png)

<sup>Created on 2022-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
