### ISSUE TITLE
Curious behaviour of `gt_plt_dist()` in RMarkdown when using `print()`

### ISSUE THREAD

**Issue by AshesITR** [jthomasmock/gtExtras#56]
First of all, thanks for this very great package!

I noticed some very curious behavior when knitting an Rmd using a results = asis chunk for generating a large number of tables in a for loop.
Here's a minimal example Rmd:

````
---
title: "Demo"
output: html_document
---

```{r}
dummy_data <- tibble::tibble(
  a = 1:2,
  b = list(1:2, 3:4)
)
```

# Auto-printing

```{r}
gt::gt(dummy_data) |>
  gtExtras::gt_plt_dist(column = b, type = "histogram")
```

# Maunal printing (using results = asis)

```{r results = 'asis'}
gt::gt(dummy_data) |>
  gtExtras::gt_plt_dist(column = b, type = "histogram") |>
  print()
```

```{r, results = 'asis'}
gt::gt(dummy_data) |>
  gtExtras::gt_plt_dist(column = b, type = "histogram") |>
  knitr::knit_print()
```
````

It produces a misaligned second row when using `base::print()` to display the table from an asis-chunk.
I'm used to `print()` just working in Rmd and it does work correctly on a plain `gt::gt()`, i.e. if I'm not using `gtExtras::gt_plt_dist()`.

![rendered document](https://user-images.githubusercontent.com/2363178/174592637-16c43151-7f5b-4db8-9374-72fc9f383eb4.png)

Now while I already found the solution (just use `knitr::knit_print()`), I still wonder why that is the case.

**Comment by jthomasmock** [comment]
I believe this is functionally solved by using `knit_print() |> cat()` in a `results='asis'` chunk.

Thus the two approaches are working:

````
---
title: "R Notebook"
output: html_document
---
```{r}
library(gt)
library(ggplot2)
dummy_data <- tibble::tibble(
  a = 1:2,
  b = list(1:2, 3:4)
)
```


```{r, results = 'asis'}
f <- function() {
  tbl <- gt::gt(dummy_data) |>
    gtExtras::gt_plt_dist(column = b, type = "histogram") |> 
    knitr::knit_print() |> 
    cat()
}

for (i in 1) {
  f()
  cat("boop.\n")
}
```


```{r, results = 'asis'}
f <- function() {
  tbl <- gt::gt(dummy_data) |>
    gtExtras::gt_plt_dist(column = b, type = "histogram") |> 
    gt::as_raw_html() |> 
    gsub(x = _, pattern = "\\s+", " ") |> 
    gt::html() |> 
    print()

}

for (i in 1) {
  f()
  cat("boop.\n")
}
```
````
![Screen Shot 2022-06-20 at 6 36 33 PM](https://user-images.githubusercontent.com/29187501/174689086-a03e26d5-7662-4dde-8419-fb8ea0c9f6ab.png)
