### ISSUE TITLE
Impossible to correctly print gt with plot from for loop

### ISSUE THREAD

**Issue by AshesITR** [jthomasmock/gtExtras#57]
Related to #56. Tested on CRAN and jthomasmock/gtExtras@f170283
If the table generating code sits in a function, there seems to be no way to correctly print a gt containing a `gt_plt_dist()` column:

````
---
title: "R Notebook"
output: html_document
---
```{r}
dummy_data <- tibble::tibble(
  a = 1:2,
  b = list(1:2, 3:4)
)
```

```{r, results = 'asis'}
f <- function() {
  gt::gt(dummy_data) |>
    gtExtras::gt_plt_dist(column = b, type = "histogram") |>
    print()
}

for (i in 1) {
  f()
  cat("boop.\n")
}
```


```{r, results = 'asis'}
f <- function() {
  gt::gt(dummy_data) |>
    gtExtras::gt_plt_dist(column = b, type = "histogram") |>
    knitr::knit_print()
}

for (i in 1) {
  f()
  cat("boop.\n")
}
```
````

Renders to
![render](https://user-images.githubusercontent.com/2363178/174594449-3d9dfc75-4d93-4261-94ec-f0bdd25c555d.png)

So using `knit_print()` (which would produce correct output) doesn't show the table at all and using `print()` shows a broken second row.

**Comment by jthomasmock** [comment]
Almost nothing is impossible with R 😉 

This is a `knitr` "problem" wrapping a `pandoc` feature. See this issue/note from Yihui on [Stackoverflow](https://stackoverflow.com/questions/40730902/r-markdown-asis-breaks-valid-html-code). 

> The problem is [Pandoc's Markdown](http://pandoc.org/MANUAL.html) treats indented lines (by four spaces) as literal code blocks (`<pre></pre>`).

You can see that behavior in your screenshot with the `<tr><td>` being printed as a literal code block.

For now you could protect against this behavior by removing any repeated whitespace.

````
```{r, results = 'asis'}
f <- function() {
  tbl <- gt::gt(dummy_data) |>
    gtExtras::gt_plt_dist(column = b, type = "histogram") |> 
    gt::as_raw_html() |> 
    gsub(x = _, pattern = "\\s+", " ") |> 
    gt::html() |> 
    print()

}

for (i in 1) {
  f()
  cat("boop.\n")
}
```
````
![Screen Shot 2022-06-20 at 10 17 43 AM](https://user-images.githubusercontent.com/29187501/174634054-e0afcb50-2857-47b3-b132-72780e9d9bcd.png)

As far as new development in `gtExtras`, I don't believe that a new print method is appropriate for the package until I can do quite a bit of testing for interactive or more traditional use as opposed to some conflicts with `knitr`. 

I was able to reproduce this behavior with just adding inline SVG in `gt` itself, so I'll explore if an issue on the default `gt` method is appropriate.

**Comment by AshesITR** [comment]
Thank you very much for the quick reply!
I'm using `gsub(pattern = "(?m)^\\s+", replacement = "", perl = TRUE)` to preserve duplicate spaces within the table just in case.
