### ISSUE TITLE
How to manually set the color of sparkline lines and extrema in gt_plt_sparkline() of gtExtras 0.4.3

### ISSUE THREAD

**Issue by ahbon123** [jthomasmock/gtExtras#73]
Hello Tom,

On **gtExtras 0.3.8**, we can set the color of sparkline lines and extrema by parameters `line_color = 'grey', range_colors = c('blue', 'red') `(refer to [gt_sparkline()](https://jthomasmock.github.io/gtExtras/reference/gt_sparkline.html))

When **gtExtras** is upgraded to version 0.4.3, we need to execute the following code to plot sparkline (refer to [gt_plt_sparkline()](https://jthomasmock.github.io/gtExtras/reference/gt_plt_sparkline.html)):

```
library(gt)
library(gtExtras)
mtcars %>%
  dplyr::group_by(cyl) %>%
  # must end up with list of data for each row in the input dataframe
  dplyr::summarize(mpg_data = list(mpg), .groups = "drop") %>%
  gt() %>%
  gt_plt_sparkline(mpg_data,
                             type = "shaded",
                             # palette =c('blue', 'red'),
                             same_limit = FALSE,
                             label = TRUE)
```
Out:

![image](https://user-images.githubusercontent.com/15428667/199895723-3cca7df2-04cc-4826-a31a-2146e693dd64.png)

I don't see parameters like `line_color `and `range_colors` in new version of  **gtExtras**, does that mean we won't be able to manually modify the color of lines and extremes or there are other ways to doing so? Thanks.

**Comment by jthomasmock** [comment]
Howdy @ahbon123 ! Please see the [documentation for that function](https://jthomasmock.github.io/gtExtras/reference/gt_plt_sparkline.html) and the `palette` argument:

> ### palette
> A character string with 5 elements indicating the colors of various components. Order matters, and **palette = sparkline color, final value color, range color low, range color high, and 'type' color (eg shading or reference lines).**

The first element of the `palette` argument is the sparkline color.

For your example snippet:

```r
library(gt)
mtcars %>%
  dplyr::group_by(cyl) %>%
  # must end up with list of data for each row in the input dataframe
  dplyr::summarize(mpg_data = list(mpg), .groups = "drop") %>%
  gt() %>%
  gt_plt_sparkline(mpg_data, palette = c("grey", "black", "red", "blue", "lightgrey"))
```

![image](https://user-images.githubusercontent.com/29187501/200613332-ff8ea132-963f-4b7b-b26b-e0dbd16f5480.png)
