### ISSUE TITLE
Target doesn't appear in `gt_plt_bullet` if it's higher than `max(column)`

### ISSUE THREAD

**Issue by zdenall** [jthomasmock/gtExtras#79]
First of all, thanks a lot for developing this package, it adds some really nice features to `gt`!

I've encountered a little bug in `gt_plt_bullet` - looks like it considers only `column` values when setting axis range:

```r
library(tibble)
library(gt)
library(gtExtras)

df <- tibble(A = 1:5, B = 1:5, C = c(3,4,5,6,7))

df %>% 
    gt() %>% 
    gt_plt_bullet(column = B, target = C)
```

<img width="295" alt="image" src="https://user-images.githubusercontent.com/11296633/218174714-868ee290-c0d7-4d1d-aeb1-eac1b4c3c0f2.png">

**Comment by jthomasmock** [comment]
Fixed in latest GitHub version - thanks for the reprex/bug report!

``` r
library(tibble)
library(gt)
library(gtExtras)

df <- tibble(A = c(1:2, -3, 4:5), B = c(1:2, -3, 4:5), C = c(3,4,5,6,7))

df %>% 
  gt() %>% 
  gt_plt_bullet(column = B, target = C) %>%
  gtsave("test.png")

knitr::include_graphics("test.png")
```

![](https://i.imgur.com/wTWOUsT.png)

<sup>Created on 2023-02-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
