### ISSUE TITLE
Fontawesome icons in tab_source_notes()

### ISSUE THREAD

**Issue by heerymichael** [jthomasmock/gtExtras#81]
Hi

I have been trying to include fontawesome social media icons within the tab_source_note of a table but every time I try when the table is exported the icon does not appear.  

The relevant code for the tab_cource_code is:

  tab_source_note(html("Table by Michael Heery &#xf099 @HEERYMICHAEL   |   DATA: UNDERDOG"))

I just wanted to check that firstly it is even possible to include fontawesome icons in this part of the table, and if so is there something I am missing that is preventing it working?

Thank you for any help you can offer

Michael

**Comment by jthomasmock** [comment]
Howdy! I don't think the raw html string method you are attempting will work as fontawesome is not available by default, but you can use the fontawesome R package:

``` r
library(gt)

fa_icon <- as.character(fontawesome::fa("twitter"))

head(mtcars) |> 
  gt() |> 
  tab_source_note(html(glue::glue("Table by Michael Heery {fa_icon} @heerymichael | DATA: UNDERDOG"))) |> 
  gtsave("test.png")

knitr::include_graphics("test.png")
```

![](https://i.imgur.com/wGbKjso.png)

<sup>Created on 2023-02-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jthomasmock** [comment]
Closed this for now, but let me know if that doesn't address your Question
