### ISSUE TITLE
FR: Dumbbell charts and maybe scale?

### ISSUE THREAD

**Issue by jthomasmock** [jthomasmock/gtExtras#82]
## Prework

- [x] Search for duplicates among the [existing issues](https://github.com/jthomasmock/gtExtras/issues) (both open and closed).

## Proposal

Create a dumbbell plot type, like this: https://fivethirtyeight.com/features/patrick-mahomes-earned-a-huge-raise-so-the-chiefs-got-creative-with-their-roster-building/

![30EDEC0A-B863-474B-9642-5E932F6C8D6B](https://user-images.githubusercontent.com/29187501/220138752-4b7ee6b7-8875-4c84-a710-2b5311755fb7.jpeg)

**Comment by brunomioto** [comment]
I think this is a dumbbell plot, if the name matters. Lollipop charts usually are just points with segments connecting to the zero line

**Comment by jthomasmock** [comment]
You are correct! Updated although I may also implement a lollipop with a thin line + point horizontally.
