### ISSUE TITLE
Improve coloring options for `gt_merge_stack`

### ISSUE THREAD

**Issue by francescoolivo** [jthomasmock/gtExtras#88]
## Prework

This topic was never mentioned explicitely, but something similar can be found in #71, #53 and #39 

## Proposal

At the moment the column created using _gt_merge_stack_ is hard to manipulate using the _tab_options_ function, it's possible to fill the cell with a color but I can't override the text color from the one passed in the function.

For instance, this works:

```
set.seed(12345)
dplyr::tibble(
	value = sample(state.name, 5),
	color_by = seq.int(10, 98, length.out = 5)
) %>%
	gt::gt() %>%
	tab_style(
		style = cell_fill(color = 'green'),
		locations = cells_body(
			columns = value,
			rows = color_by >= 80
		)
	)
```

But this does not work.
```
set.seed(12345)
dplyr::tibble(
	value = sample(state.name, 5),
	color_by = seq.int(10, 98, length.out = 5)
) %>%
	gt::gt() %>%
	gt_merge_stack(col1 = value, col2 = color_by) %>%
	tab_style(
		style = cell_text(color = 'green'),
		locations = cells_body(
			columns = value,
			rows = color_by >= 80
		)
	)
```

I think it would be a useful feature.

Also, I noticed that when you stack two floats you loose the decimal formatting on `col2`

**Comment by francescoolivo** [comment]
Makes sense. Maybe a less elegant option may be to pass the colors as columns containing a color, like in _scale_fill_identity`. For instance

```
set.seed(12345)
dplyr::tibble(
	value = sample(state.name, 5),
	color_by = seq.int(10, 98, length.out = 5)
) %>%
        mutate(color_col = case_when(color_by > 80 ~ 'green', TRUE ~ 'black')) %>%
	gt::gt() %>%
	gt_merge_stack(col1 = value, col2 = color_by, palette = c(color_col, 'black'))
```

Don't worry if it's a mess to implement, I can simply fill the whole cell, I realize that storing the color is not particularly elegant so it's not the best option to implement.

**Comment by jthomasmock** [comment]
Yah - part of this is that there are tradeoffs in one solution for another - at this point, the function is very focused on it's narrow use case. Thank you for the request though!
