### ISSUE TITLE
Margins of gt_two_column_layout

### ISSUE THREAD

**Issue by petermott** [jthomasmock/gtExtras#92]
## Question
In Rstudio rmarkdown the output of gt_two_column_layout appears to float the first table to the left and the second to the right. With narrow tables put side-by-side just for comparison this results in a large gap in the middle of the tables:
![2023-06-09 11_18_34-Chapter 8 Exercises - Opera](https://github.com/jthomasmock/gtExtras/assets/7861523/6cccf3e7-d229-48f7-9534-6154ee10f26c)

I can fix this by enclosing the rmarkdown code block in HTML tags:

![image_2023-06-09_112316945](https://github.com/jthomasmock/gtExtras/assets/7861523/e9068394-5f27-48d1-8fb9-ddb1dab4b94a)

The result is then:
![image_2023-06-09_112752398](https://github.com/jthomasmock/gtExtras/assets/7861523/e3c235fb-218b-4861-ad0f-42ce6ed6f93d)

Is there a way to provide this information to the `gt_two_column_layout` command?

If not  I would like to request this as a feature -  something like
 `gt_two_column_layout(tables, margins=c(250,250)`

**Comment by jthomasmock** [comment]
Thanks for the overview! 

`gt_two_column_layout()` is intended to be used with `gt_save_extra()` for screenshots where you don't have additional controls such as RMarkdown. 

You are correct in that other HTML-native mechanisms available for RMarkdown and Quarto can further control the layout of tables in a document. Closing this issue as `gt_two_column_layout()` is not intended to replace capabilities available for HTML documents.
