### ISSUE TITLE
gt_plt_sparkline label

### ISSUE THREAD

**Issue by frzambra** [jthomasmock/gtExtras#95]
Hi all, I'm using `gt_plt_sparkline`, but I don't know from where the label takes its value or if I can supply a specific one. I suppose the default value is the mean, but:

 ```r
mtcars |> group_by(cyl) |> summarize(mpd = mean(mpg))
 A tibble: 3 × 2
    cyl   mpd
  <dbl> <dbl>
1     4  26.7
2     6  19.7
3     8  15.1
```

![imagen](https://github.com/jthomasmock/gtExtras/assets/4713428/d287a9e4-a954-4ef2-83af-0418fd1245bd)

I want to use the trend as the label, but I must add another column. It would be good that the user can assign the value for the label from another column.

**Comment by jthomasmock** [comment]
Howdy - the label is the final value of the data. There isn't an option to change that, just to turn on/off the display of that final value.
