### ISSUE TITLE
All negative values in gt_plt_bar()

### ISSUE THREAD

**Issue by daneel6672** [jthomasmock/gtExtras#97]
## Description

gt_plt_bar() has missing bar plots when all the values in the bar plot are negative

## Reproducible example

```
mtcars_test <- mtcars
mtcars_test[,"mpg"] <- -mtcars_test[,"mpg"]
mtcars_test %>%
  head() %>%
  gt() %>%
  gt_plt_bar(column = mpg, keep_column = TRUE)
```

## Expected result

A bar plot with all negative values (zero on the right for all of them)

![mpg example](https://github.com/jthomasmock/gtExtras/assets/20476435/475eb985-4948-4552-a297-022ef9ea3d28)

**Comment by jthomasmock** [comment]
Howdy!

All the plots appear correct to me unless I'm missing something?

The bar charts have a vertical black line indicating zero, so left-facing  bars are negative and right-facing are positive.

``` r
library(gtExtras)
#> Loading required package: gt

mtcars_test <- mtcars
mtcars_test[,"mpg"] <- -mtcars_test[,"mpg"]
mtcars_test %>%
  head() %>%
  dplyr::mutate(mpg = ifelse(mpg == -18.1, 18.1, mpg)) |> 
  gt() %>%
  gt_plt_bar(column = mpg, keep_column = TRUE) |> 
  gtExtras::gt_reprex_image()
```

<img src="https://i.imgur.com/DI7LWhU.png" width="1480" />

<sup>Created on 2023-08-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jthomasmock** [comment]
Closing for now, but let me know if I misunderstood the question.

**Comment by daneel6672** [comment]
The picture I added was what the results are supposed to look like (I edited the actual picture. When I run the reproducible example I get blank graphs

![image](https://github.com/jthomasmock/gtExtras/assets/20476435/2fd47236-1c6f-49f6-9deb-458e0dc86ddd)

**Comment by jthomasmock** [comment]
Hi @daneel6672 - this is what I'm seeing with the latest version of `gtExtras`:

```r
library(gtExtras)

mtcars_test <- mtcars
mtcars_test[,"mpg"] <- -mtcars_test[,"mpg"]
mtcars_test %>%
  head() %>%
  gt() %>%
  gt_plt_bar(column = mpg, keep_column = TRUE)
```

![image](https://github.com/jthomasmock/gtExtras/assets/29187501/fec0f4d5-4668-4dce-933c-ac2dd80f196e)

**Comment by daneel6672** [comment]
I had version gtExtras_0.4.5 which generates that blank output. I used your repository and upgraded to gtExtras_0.5.0 and now I see the same output as you. Thanks for your help and for making and maintaining such a great package.
